line-length = 120
indent-width = 4

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
    "ALL",  # Picks up new rules with updates to ruff
    # Rules to include even if a parent is listed as ignored:
    "W605", "D419", "G010", "G101", "G2", "RET501", "RET502", "RET503",
]
extend-ignore = [
    # Explicit conflicts with ruff's auto-formatter:
    "W191", "E111", "E114", "E117", "D206", "D300", "Q000", "Q001", "Q002", "Q003", "Q004", "COM812", "COM819", "E501",
    # No need to be so strict on comments:
    "TD002", "TD003", "FIX", "ERA",
    # Don't care:
    "C90", "D", "DOC", "ANN002", "ANN003", "ANN401", "S104", "S113", "S311", "FBT",
    "CPY", "C408", "EM", "G", "RSE102", "RET", "TC", "PTH123",
    "PLR09", "PLR2004", "TRY003", "TRY301",
    # Actually makes code harder to read:
    "UP015", "PT003", "SIM108",
]

[lint.per-file-ignores]
"**/tests/**" = [
    "S101",  # Allow `assert` in tests
    "INP001",  # Don't require `__init__.py` in test dirs
]

[lint.flake8-annotations]
suppress-none-returning = true
suppress-dummy-args = true

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
combine-as-imports = true

[lint.pydocstyle]
convention = "google"
